/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mysql.ide;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class RenameTable extends javax.swing.JFrame {
String uid;
    /**
     * Creates new form CreateDB
     */
    public RenameTable() {
        initComponents();
    }
    public RenameTable(String uid) {
        initComponents();
        this.uid=uid;
        
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        redb = new javax.swing.JTextField();
        cdl = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ref = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        ret = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(0, 181, 240));
        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mysql/ide/databasere.png"))); // NOI18N
        jLabel1.setText("MySQL-IDE");
        jLabel1.setIconTextGap(10);
        jPanel2.add(jLabel1);
        jLabel1.setBounds(200, 0, 170, 40);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mysql/ide/error (1).png"))); // NOI18N
        jLabel3.setToolTipText("Close");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel3);
        jLabel3.setBounds(460, 0, 20, 30);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 550, 40);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("Database Name :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(110, 90, 140, 30);

        redb.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jPanel1.add(redb);
        redb.setBounds(250, 90, 130, 30);

        cdl.setBackground(new java.awt.Color(0, 181, 240));
        cdl.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        cdl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cdl.setText("Rename");
        cdl.setToolTipText("");
        cdl.setOpaque(true);
        cdl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cdlMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cdlMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cdlMouseExited(evt);
            }
        });
        jPanel1.add(cdl);
        cdl.setBounds(390, 170, 91, 30);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mysql/ide/columns.png"))); // NOI18N
        jLabel4.setText("Rename Table");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(190, 40, 160, 30);

        ref.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jPanel1.add(ref);
        ref.setBounds(70, 170, 120, 30);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setText("From :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(10, 170, 60, 30);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setText("Table Name :-");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(10, 130, 110, 30);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setText("To :");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(210, 170, 40, 30);

        ret.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jPanel1.add(ret);
        ret.setBounds(250, 170, 120, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cdlMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cdlMouseEntered
        // TODO add your handling code here:
        cdl.setBackground(new Color(0,255,255));
    }//GEN-LAST:event_cdlMouseEntered

    private void cdlMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cdlMouseExited
        // TODO add your handling code here:
        cdl.setBackground(new Color(0,181,240));
    }//GEN-LAST:event_cdlMouseExited

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
       this.setVisible(false);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void cdlMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cdlMouseClicked
        // TODO add your handling code here:
          try {

                Class.forName("com.mysql.cj.jdbc.Driver").newInstance();

               Connection con= DriverManager.getConnection("jdbc:mysql://localhost:3306/"+(uid+redb.getText()),"root","root1799@");
               
               String sq="alter table "+ref.getText()+" rename to "+ret.getText();   
               PreparedStatement pstm=con.prepareStatement(sq);
               pstm.executeUpdate();
              
                JOptionPane.showMessageDialog(ret,"Table Renamed.");
                this.setVisible(false);
                
   }catch(Exception e)
   {
     if(e.toString().substring(0, 50).equals("java.sql.SQLSyntaxErrorException: Unknown database"))
           JOptionPane.showMessageDialog(ret, "Entered Database Dosen't Exist");
     else  if(e.toString().substring(0, 47).equals("java.sql.SQLSyntaxErrorException: Unknown table"))
           JOptionPane.showMessageDialog(ret, "Entered Table Dosen't Exist");
   } 
 
    }//GEN-LAST:event_cdlMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RenameTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RenameTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RenameTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RenameTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RenameTable().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cdl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField redb;
    private javax.swing.JTextField ref;
    private javax.swing.JTextField ret;
    // End of variables declaration//GEN-END:variables
}
